config/routes.rb
Rails.application.routes.draw do
  root 'orders#index'#定義首頁

  #resources :orders
  #order/1/comment
  resources :orders do
    member do # 客製化連結
      post :vote
      # 這樣會產出 orders/1/vote
    end
    # 嵌套/巢狀路由，這樣可以產生出 orders/1/comments/ 的 url
    resources :comments, only: [:create] do
      member do
        post :vote
        # 產出 orders/1/comments/1/vote
      end
    end
  end


  resources :users, only: [:new, :create]
  get '/register', to: 'users#new'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # config/routes.rb
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end
#/config/routes.rb 是一個 Rails 專案管理路由以及相對應 Controller Action 的檔案，Rails 專案的路由都是在這裡設定

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord
  validates :name, presence: true
  validates :name, length: { minimum: 2 }
  validates :name, length: { maximum: 200 }
  validates :phone, presence: true

  has_many :comments
  has_many :votes, as: :voteable

  def up_votes
    self.votes.where(vote: true).length
  end

  def down_votes
    self.votes.where(vote: false).length
  end

  def total_votes
    up_votes - down_votes
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password validation: false

    has_many :comments
    has_many :votes, as: :voteable
end

app/models/vote.rb
class Vote < ApplicationRecord
  # 關聯的設定可以給別名，foreign key 和相關連的 model 需要自己設定  
  belongs_to :creator, foreign_key: :user_id, class_name: "User"

  belongs_to :voteable, polymorphic: true

  validates_uniqueness_of :creator, scope: [:voteable_type, :voteable_id]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  
  helper_method :current_user, :logged_in?

  def current_user 
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
     # 找相關連的訂單
     @order = Order.find(params[:order_id])
     # build 與 new 的意思一樣
     @comment = @order.comments.build(params.require(:comment).permit(:content))
     # 綁定現在登入的使用者
     @comment.user = current_user
     
     if @comment.save
       redirect_to order_path(@order)
     else
       redirect_to order_path(@order)
     end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]#在執行特定方法時先值行:set_order

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.page(params[:page]).per(5)
    # binding.pry
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @commont = @order.comments
    @comment = Comment.new
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save #如果回傳成功
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def vote
    @order = Order.find(params[:id])
    @vote = Vote.create(voteable: @order, creator: current_user, vote: params[:vote])

    redirect_to root_path
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :phone, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    #登入頁面使用
  end

  def create
    #尋找使用者
    user = User.find_by(name: params[:name])   
    #驗證使用者，若成功，就建立一個 session，把 user_id 放入 session hash
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    #登出畫面使用，刪除 session hash 裡面的 user_id
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# app/controllers/userss_controllers.rb

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  private 

  def user_params
    params.require(:user).permit(:name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
    <div class="navbar-header">
        <%= link_to "WWW訂便當系統", orders_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <%if logged_in? %>
            <li><%= link_to '新增訂單', new_order_path %></li>
            <li><%= link_to '登出', logout_path, data: { confirm: 'Are you sure?' } %></li>
          <% else %>
            <li><%= link_to '登入', login_path %></li>
            <li><%= link_to '註冊', register_path %></li>
          <% end %>
        </ul>
    </div>
    </div>
</nav>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dinbento</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <%= render 'layouts/nav'%>
    <%= yield %>

  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %><!--印出錯誤-->
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<%= render 'shared/title', title: "Editing Order" %>
<!--h1>Editing Order</h1-->

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>
<%= render 'shared/title', title: "Orders" %>


<table>
  <thead>
    <tr>
      <th>票數</th>
      <th>讚</th>
      <th>噓</th>
      <th><%= t("order.name") %></th>
      <th>Phone</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.total_votes %></td>
        <td>
          <%= link_to '讚', vote_order_path(order, vote: true), class: "btn btn-primary", method: 'post' %>
        </td>
        <td>
          <%= link_to vote_order_path(order, vote: false), class: "btn btn-danger", method: 'post' do %>
          噓
          <% end %>
        </td>
        <td><%= order.name %></td>
        <td><%= order.phone %></td>
        <td><%= order.description %></td>
        <td><%= link_to 'Show', order_path(order), class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_order_path(order), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', order_path(order), class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @orders %>
<br>
<%if logged_in? %>
  <%= link_to 'New Order', new_order_path, class:"btn btn-primary" %>
<%end %>

app/views/orders/new.html.erb
<%= render 'shared/title', title: "New Order" %>
<!--h1>New Order</h1-->

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<%= render 'shared/title', title: "Show" %>

<p id="notice"><%= notice %></p>

 <table class="table">
   <tr>
     <td><strong>姓名:</strong></td>
     <td><%= @order.name %></td>
   </tr>
     <td><strong>Phone:</strong></td>
     <td><%= @order.phone %></td>
   <tr>
     <td><strong>訂單內容:</strong></td>
     <td><%= @order.description %></td>
   </tr>
 </table>
 
 <h4>留言區:</h4>
 
 <!% @order.comments.order("created_at DESC").each do |comment| %-->
 <% @order.comments.reverse.each do |comment| %>
   <div class="row">
     <div class="col-md-6 well">
       <p>
         <%= comment.content %>
       </p>
       <br>
       <small>留言者： </small><%= "#{comment.user.name}" %>
       <br>
       <small>Time： </small><%= "#{comment.created_at}"%>
     </div>
   </div>
 <% end %>
 
 <% if logged_in? %>
   <h4>請留言:</h4>
   <%= form_for [@order, @comment] do |f| %>
     <div class="row">
       <%= f.text_area :content, rows: 5, class: 'col-md-4' %>
       <div class="col-md-2">
         <%= f.submit '留言', class: 'btn btn-primary' %>
       </div>
     </div>
     <br>
   <% end %> 
<% end %>

app/views/shared/_title.html.erb
<h1 class="text-center"><%= title%></h1>
<hr>

app/views/users/new.html.erb
<h4>註冊</h4>

<div class="well col-md-6">
  <%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <br>
    <%= f.password_field :password%>
  </div>
  <br>
  <%= f.submit(@user.new_record? ? 'Register' : 'Update Profile', class: 'btn btn-success') %>
  <% end %>
</div>